--- 
- name: Create directory layout
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items: "{{ db_directories }}"
  when: item | length > 0  
        
- include_tasks: 
    file: tenant.yml
  loop: "{{ [platform] + tenants }}"
  loop_control:
    loop_var: tenant    
    


